package base;

import java.io.IOException;
import database.DatabaseServer;
import net.jxta.discovery.DiscoveryService;
import net.jxta.peergroup.PeerGroup;
import net.jxta.pipe.InputPipe;
import net.jxta.pipe.OutputPipe;
import net.jxta.pipe.PipeService;
import net.jxta.platform.NetworkConfigurator;
import net.jxta.platform.NetworkManager;
import net.jxta.protocol.PipeAdvertisement;

/**
 * Stores the the configuration, and all needed variables
 *   
 * @author Torsten Burschka
 */

public class Configuration {

	/**
	 * Project name
	 */
	public String project = "MarsMissionII";
	
	/**
	 * Node name 
	 */
	public String nodeName = "Node";
	
	/**
	 * Node principal
	 */
	public String principal = nodeName;
	
	/**
	 * Node password
	 */
	public String password = "mars2007";
	
	public static String rendezvousFile = "rdv.lst";
	
	public static String relayFile = "rly.lst";
	
	public static String globalPath = "";
	
	public static String projectPath = "";
	
	/**
	 * PeerGroup
	 */
	public PeerGroup netPeerGroup = null;

	/**
	 * Stores the configuration
	 */
	public NetworkConfigurator configuration = null;

	/**
	 * Pipe Advertisement
	 */
	public PipeAdvertisement pipeAdv = null;
	
	/**
	 * Pipe Service
	 */
	public PipeService pipeServ = null;
	
	/**
	 * Discovery Service
	 */
	public DiscoveryService discServ = null;
	
	/**
	 * NetworkManager
	 */
	public NetworkManager manager; 
	
	/**
	 * Input pipe
	 */
	public InputPipe inputPipe = null;
	
	/**
	 * Output pipe
	 */
	public OutputPipe outputPipe = null;

	/**
	 * Message container for outgoing messages
	 */
	public net.jxta.endpoint.Message message_out = null;

	/**
	 * Time to wait for a rendezvous connection in msec
	 */
	public long waitTime = 10000;	
	
	public Configuration (String profile) {
		this.nodeName = profile;
		System.setProperty("JXTA_HOME","."+this.project+"_"+this.nodeName);
		this.configuration = new NetworkConfigurator();
		setProjectPath();
		setGlobalPath();
		if (!configuration.exists()) {
			createConfig();
		} else {
			System.out.println(nodeName+": Configuration found.");
			RendezvousList.addHostAdresses();
		}
		System.out.println("create connection to message database.");
		DatabaseServer.createDatabase();
	}
	
	private void createConfig() {
		// Create a new configuration with a new name, principal, and pass
		System.out.println("\n"+this.nodeName+": No configuration found. Autogenerate a new configuration.");
		configuration.setName(nodeName);
		configuration.setPrincipal(nodeName);
		configuration.setPassword(password);
		configuration.setDescription("Autogenerated Platform Config Advertisement.");
		configuration.setTcpEnabled(true);
		configuration.setTcpIncoming(true);
		configuration.setTcpOutgoing(true);
		configuration.setHttpEnabled(false);
		configuration.setHttpIncoming(false);
		configuration.setHttpOutgoing(false);
		configuration.setUseMulticast(false);
		configuration.setUseOnlyRendezvousSeeds(true);
		configuration.addRdvSeedingURI(Utilities.toURI(Configuration.getProjectPath()+rendezvousFile));
		configuration.setTcpPort(9702);
		configuration.setTcpEndPort(9702);
		configuration.setTcpStartPort(9702);
		configuration.setUseOnlyRelaySeeds(false);
		configuration.setMode(NetworkConfigurator.TCP_CLIENT
				+ NetworkConfigurator.TCP_SERVER);
		try {
			// persist it
			configuration.save();

		} catch (IOException ioe) {
			System.err.println("\n"+this.nodeName+": Could not save the configuration!");
			System.err.println("\n"+this.nodeName+": Error Message:");
			ioe.printStackTrace();
			System.err.println();
		}
		RendezvousList.addHostAdresses();
	}
	
	public void setAsRendezvous() {
		System.out.println("\n"+this.nodeName+":Set configuration to rendezvous server.");
		configuration.setHttpEnabled(true);
	    configuration.setHttpIncoming(true);
	    configuration.setHttpOutgoing(true);
	    configuration.setHttpPort(9700);
	    configuration.setTcpEnabled(true);
	    configuration.setTcpIncoming(true);
	    configuration.setTcpOutgoing(true);
	    configuration.setUseMulticast(false);
	    configuration.setTcpPort(9701);
	    configuration.setUseOnlyRendezvousSeeds(false);
	    configuration.setUseOnlyRelaySeeds(false);
	    configuration.setTcpEndPort(9701);
	    configuration.setTcpStartPort(9701);
	    configuration.addRdvSeedingURI(Utilities.toURI(Configuration.getProjectPath()+rendezvousFile));
	    configuration.addRelaySeedingURI(Utilities.toURI(Configuration.getProjectPath()+rendezvousFile));
	    configuration.setMode(NetworkConfigurator.RDV_SERVER
	        +NetworkConfigurator.TCP_SERVER+NetworkConfigurator.TCP_CLIENT
	        +NetworkConfigurator.RELAY_SERVER+NetworkConfigurator.HTTP_SERVER
	        +NetworkConfigurator.HTTP_CLIENT);
		try {
			// persist it
			configuration.save();

		} catch (IOException ioe) {
			System.err.println("\n"+this.nodeName+": Could not save the configuration!");
			System.err.println("\n"+this.nodeName+": Error Message:");
			ioe.printStackTrace();
			System.err.println();
		}
	}
	
	private void setProjectPath() {
		projectPath = System.getProperty("JXTA_HOME") + "\\";
	}
	
	private void setGlobalPath() {
		globalPath = System.getProperty("JXTA_HOME").replaceAll("\\"+"."+this.project+"_"+this.nodeName,"");
	}

	public static String getGlobalPath() {
		return globalPath;
	}

	public static String getProjectPath() {
		return projectPath;
	}
}